import type { UserPresetTask, ProfileType } from '@/types';

// Version for the default routines data structure
export const ROUTINE_TEMPLATE_VERSION = 27;

const creativeProfessionalRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
    { name: "Morning Idea Dump / Journaling", duration: 15, icon: "BookOpen", category: "Morning Routine" },
    { name: "Light Stretching or Mobility", duration: 15, icon: "StretchHorizontal", category: "Morning Routine" },
    { name: "Mindful Breakfast", duration: 20, icon: "Utensils", category: "Morning Routine" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Primary Work Session" },
    { name: "Uninterrupted Deep Creative Work", duration: 120, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "Inspiration & Research Block", duration: 60, icon: "Lightbulb", category: "Primary Work Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Lunch Break" },
    { name: "Mindful Meal (away from desk)", duration: 30, icon: "Utensils", category: "Lunch Break" },
    { name: "Short Walk", duration: 15, icon: "Footprints", category: "Lunch Break" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Afternoon Session" },
    { name: "Skill Practice / Tutorial", duration: 45, icon: "Wrench", category: "Afternoon Session" },
    { name: "Admin & Client Communication", duration: 60, icon: "Mail", category: "Afternoon Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Post-Work Decompression" },
    { name: "Main Exercise / Workout", duration: 45, icon: "Dumbbell", category: "Post-Work Decompression" },
    { name: "Relaxing Hobby", duration: 60, icon: "Gamepad2", category: "Post-Work Decompression" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Routine" },
    { name: "Mindful Dinner", duration: 30, icon: "Utensils", category: "Evening Routine" },
    { name: "Social Time with Family/Friends", duration: 60, icon: "Users", category: "Evening Routine" },
    { name: "Drink a small glass of water", duration: 1, icon: "Droplets", category: "Bedtime Routine" },
    { name: "Final Idea Capture (on paper)", duration: 5, icon: "PenSquare", category: "Bedtime Routine" },
    { name: "Digital Detox (no screens)", duration: 30, icon: "Smartphone", category: "Bedtime Routine" },
    { name: "Read Fiction or Listen to Calming Music", duration: 20, icon: "Headphones", category: "Bedtime Routine" },
];

const businessProfessionalRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
    { name: "Workout/Exercise", duration: 30, icon: "Dumbbell", category: "Morning Routine" },
    { name: "Review Day's Top 3 Priorities", duration: 10, icon: "ListChecks", category: "Morning Routine" },
    { name: "Breakfast & Scan News", duration: 20, icon: "Utensils", category: "Morning Routine" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Primary Work Session" },
    { name: "Tackle Most Important Task", duration: 90, icon: "Target", category: "Primary Work Session" },
    { name: "Strategic Thinking / \"No-Meeting\" Block", duration: 60, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Lunch Break" },
    { name: "Power Lunch / Quick Walk", duration: 45, icon: "Footprints", category: "Lunch Break" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Afternoon Session" },
    { name: "Meetings & Collaborative Tasks", duration: 120, icon: "Users", category: "Afternoon Session" },
    { name: "Scan & Reply to Emails", duration: 30, icon: "Mail", category: "Afternoon Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Post-Work Decompression" },
    { name: "End-of-Day Review & Shutdown Ritual", duration: 15, icon: "Power", category: "Post-Work Decompression" },
    { name: "Hobby / Leisure", duration: 60, icon: "Gamepad2", category: "Post-Work Decompression" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Routine" },
    { name: "Dinner with Family/Friends (no work talk)", duration: 45, icon: "Utensils", category: "Evening Routine" },
    { name: "Drink a small glass of water", duration: 1, icon: "Droplets", category: "Bedtime Routine" },
    { name: "Prepare for the Next Day", duration: 10, icon: "ShoppingBag", category: "Bedtime Routine" },
    { name: "Light Reading (non-work related)", duration: 20, icon: "BookOpen", category: "Bedtime Routine" },
    { name: "Meditation for Stress Release", duration: 10, icon: "Wind", category: "Bedtime Routine" },
];

const technicalProfessionalRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
    { name: "Meditation for Focus", duration: 10, icon: "Wind", category: "Morning Routine" },
    { name: "Review Tech News / Documentation", duration: 20, icon: "FileCode", category: "Morning Routine" },
    { name: "Breakfast (no screens)", duration: 20, icon: "Utensils", category: "Morning Routine" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Primary Work Session" },
    { name: "Deep Work Coding / Analysis Session", duration: 50, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "Short Break", duration: 10, icon: "Coffee", category: "Primary Work Session" },
    { name: "Deep Work Coding / Analysis Session", duration: 50, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "CRITICAL: Hourly Eye Strain Break", duration: 1, icon: "Eye", category: "Primary Work Session" },
    { name: "Short Break", duration: 10, icon: "Coffee", category: "Primary Work Session" },
    { name: "Deep Work Coding / Analysis Session", duration: 50, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Lunch Break" },
    { name: "Screen-Free Lunch & Walk", duration: 45, icon: "Footprints", category: "Lunch Break" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Afternoon Session" },
    { name: "Code Reviews / Meetings", duration: 60, icon: "Users", category: "Afternoon Session" },
    { name: "Writing Documentation", duration: 30, icon: "PenSquare", category: "Afternoon Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Post-Work Decompression" },
    { name: "Strength Training or Cardio", duration: 45, icon: "Dumbbell", category: "Post-Work Decompression" },
    { name: "Analog Hobby", duration: 60, icon: "Puzzle", category: "Post-Work Decompression" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Routine" },
    { name: "Mindful Dinner", duration: 30, icon: "Utensils", category: "Evening Routine" },
    { name: "Personal Project / Learning", duration: 45, icon: "Lightbulb", category: "Evening Routine" },
    { name: "Drink a small glass of water", duration: 1, icon: "Droplets", category: "Bedtime Routine" },
    { name: "Strict Screen Cutoff", duration: 60, icon: "Smartphone", category: "Bedtime Routine" },
    { name: "Stretching for desk posture", duration: 10, icon: "StretchHorizontal", category: "Bedtime Routine" },
    { name: "Read a physical book", duration: 20, icon: "BookOpen", category: "Bedtime Routine" },
];

const onTheGoRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Prep" },
    { name: "Route & Schedule Review", duration: 15, icon: "Map", category: "Morning Prep" },
    { name: "High-Energy Breakfast", duration: 20, icon: "Utensils", category: "Morning Prep" },
    { name: "Drink water before leaving", duration: 1, icon: "Droplets", category: "On the Road" },
    { name: "In-Car Mental Reset", duration: 5, icon: "Wind", category: "On the Road" },
    { name: "Packed Lunch Break", duration: 20, icon: "Utensils", category: "On the Road" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Post-Work Admin" },
    { name: "Log Reports & Admin on Mobile", duration: 20, icon: "Smartphone", category: "Post-Work Admin" },
    { name: "Restock & Prep for Tomorrow", duration: 10, icon: "ShoppingBag", category: "Post-Work Admin" },
    { name: "Dinner", duration: 30, icon: "Utensils", category: "Evening & Bedtime" },
    { name: "Stretching for physical tension", duration: 15, icon: "StretchHorizontal", category: "Evening & Bedtime" },
    { name: "Warm shower to relax", duration: 15, icon: "ShowerHead", category: "Evening & Bedtime" },
];

const healthcareRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Pre-Shift Routine" },
    { name: "High-Energy Meal", duration: 30, icon: "Utensils", category: "Pre-Shift Routine" },
    { name: "Gentle Movement & Mental Prep", duration: 15, icon: "BrainCircuit", category: "Pre-Shift Routine" },
    { name: "Drink water frequently", duration: 1, icon: "Droplets", category: "During Shift" },
    { name: "During-Shift Micro-Reset", duration: 1, icon: "Wind", category: "During Shift" },
    { name: "Eat small, healthy snacks", duration: 10, icon: "Apple", category: "During Shift" },
    { name: "Rehydrate immediately with water", duration: 1, icon: "Droplets", category: "Post-Shift Decompression" },
    { name: "Mindful Commute", duration: 20, icon: "Headphones", category: "Post-Shift Decompression" },
    { name: "Recovery Meal & Connect with Family", duration: 45, icon: "Utensils", category: "Post-Shift Decompression" },
    { name: "Warm shower to signal 'end of day'", duration: 15, icon: "ShowerHead", category: "Post-Shift Decompression" },
];

const dayOffRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Recovery" },
    { name: "Gentle Stretching or a walk", duration: 20, icon: "Footprints", category: "Morning Recovery" },
    { name: "Leisurely Breakfast", duration: 30, icon: "Coffee", category: "Morning Recovery" },
    { name: "Run errands, appointments, groceries", duration: 90, icon: "ShoppingCart", category: "Afternoon Life Admin & Recharge" },
    { name: "Dedicate time to a relaxing hobby", duration: 60, icon: "Gamepad2", category: "Afternoon Life Admin & Recharge" },
    { name: "Connect with friends or family", duration: 60, icon: "Users", category: "Afternoon Life Admin & Recharge" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening & Bedtime Reset" },
    { name: "Mindful Dinner", duration: 30, icon: "Utensils", category: "Evening & Bedtime Reset" },
    { name: "Relaxing entertainment", duration: 60, icon: "Tv", category: "Evening & Bedtime Reset" },
    { name: "Consistent bedtime routine", duration: 30, icon: "Bed", category: "Evening & Bedtime Reset" },
];

const dayOffRoutineHealthcare: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Recovery" },
    { name: "Gentle Stretching or a walk", duration: 20, icon: "Footprints", category: "Morning Recovery" },
    { name: "Leisurely Breakfast", duration: 30, icon: "Coffee", category: "Morning Recovery" },
    { name: "Run errands, appointments, groceries", duration: 90, icon: "ShoppingCart", category: "Afternoon Life Admin & Recharge" },
    { name: "Dedicate time to a relaxing hobby", duration: 60, icon: "Gamepad2", category: "Afternoon Life Admin & Recharge" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening & Bedtime Reset" },
    { name: "Mindful Dinner", duration: 30, icon: "Utensils", category: "Evening & Bedtime Reset" },
    { name: "Journaling to unload stress", duration: 10, icon: "BookOpen", category: "Evening & Bedtime Reset" },
    { name: "Consistent bedtime routine", duration: 30, icon: "Bed", category: "Evening & Bedtime Reset" },
];

const analystRoutine: Omit<UserPresetTask, "id" | "order" | "profession">[] = [
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
    { name: "Meditation for Focus", duration: 10, icon: "Wind", category: "Morning Routine" },
    { name: "Breakfast (no screens)", duration: 20, icon: "Utensils", category: "Morning Routine" },
    { name: "Commute to Office", duration: 30, icon: "Car", category: "Morning Routine" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Primary Work Session" },
    { name: "Team Stand-up & Daily Sync", duration: 15, icon: "Users", category: "Primary Work Session" },
    { name: "Deep Work: Data Querying & Analysis", duration: 120, icon: "BrainCircuit", category: "Primary Work Session" },
    { name: "Coffee Break & Stretch", duration: 15, icon: "Coffee", category: "Primary Work Session" },
    { name: "Continue Deep Work", duration: 120, icon: "Target", category: "Primary Work Session" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Lunch Break" },
    { name: "Lunch with Colleagues", duration: 45, icon: "Utensils", category: "Lunch Break" },
    { name: "Short Walk", duration: 15, icon: "Footprints", category: "Lunch Break" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Afternoon Session" },
    { name: "Stakeholder Meetings", duration: 60, icon: "Presentation", category: "Afternoon Session" },
    { name: "Building Reports & Visualizations", duration: 60, icon: "BarChart", category: "Afternoon Session" },
    { name: "Plan Tomorrow's Priorities", duration: 15, icon: "ListChecks", category: "Afternoon Session" },
    { name: "Commute from Office", duration: 30, icon: "Car", category: "Post-Work Decompression" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Post-Work Decompression" },
    { name: "Strength Training or Cardio", duration: 45, icon: "Dumbbell", category: "Post-Work Decompression" },
    { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening & Bedtime" },
    { name: "Mindful Dinner", duration: 30, icon: "Utensils", category: "Evening & Bedtime" },
    { name: "Strict Screen Cutoff", duration: 30, icon: "Smartphone", category: "Evening & Bedtime" },
    { name: "Read a physical book", duration: 20, icon: "BookOpen", category: "Evening & Bedtime" },
];


export const defaultRoutines: { version: number, routines: { [key in ProfileType]: Omit<UserPresetTask, "id" | "order" | "profession">[] } } = {
    version: ROUTINE_TEMPLATE_VERSION,
    routines: {
        "Analyst": analystRoutine,
        "Artist": creativeProfessionalRoutine,
        "Consultant": businessProfessionalRoutine,
        "Content Creator": creativeProfessionalRoutine,
        "Designer": creativeProfessionalRoutine,
        "Educator": [
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
            { name: "Freshen Up & Get Ready", duration: 15, icon: "ShowerHead", category: "Morning Routine" },
            { name: "Breakfast", duration: 20, icon: "Utensils", category: "Morning Routine" },
            { name: "Review Lesson Plan", duration: 20, icon: "ListChecks", category: "Morning Routine" },
            { name: "Prepare Materials", duration: 25, icon: "ShoppingBag", category: "Morning Routine" },
            { name: "Teaching Block 1", duration: 90, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Grading & Feedback", duration: 60, icon: "PenTool", category: "Work & Focus" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Work & Focus" },
            { name: "Lunch", duration: 25, icon: "Utensils", category: "Breaks & Meals" },
            { name: "Short Walk", duration: 5, icon: "Footprints", category: "Breaks & Meals" },
            { name: "Teaching Block 2", duration: 90, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Parent Communication", duration: 30, icon: "Mail", category: "Work & Focus" },
            { name: "De-stress Activity (Walk, etc.)", duration: 30, icon: "Footprints", category: "Health & Wellness" },
            { name: "Dinner", duration: 45, icon: "Utensils", category: "Evening Wind-down" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Wind-down" },
            { name: "Personal Time / Hobby", duration: 60, icon: "Gamepad2", category: "Evening Wind-down" },
            { name: "Plan Tomorrow's Top 3", duration: 15, icon: "Wrench", category: "Bedtime Routine" },
            { name: "Read for Pleasure", duration: 20, icon: "BookOpen", category: "Bedtime Routine" },
            { name: "Bedtime", duration: 0, icon: "Bed", category: "Bedtime Routine" },
        ],
        "Entrepreneur": businessProfessionalRoutine,
        "Freelancer": [
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
            { name: "Freshen Up & Get Ready", duration: 15, icon: "ShowerHead", category: "Morning Routine" },
            { name: "Breakfast", duration: 20, icon: "Utensils", category: "Morning Routine" },
            { name: "Prioritize Client Work", duration: 20, icon: "ListChecks", category: "Morning Routine" },
            { name: "Morning Walk", duration: 20, icon: "Footprints", category: "Morning Routine" },
            { name: "Client Project A - Deep Work", duration: 120, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Client Communication", duration: 30, icon: "Mail", category: "Work & Focus" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Work & Focus" },
            { name: "Lunch", duration: 25, icon: "Utensils", category: "Breaks & Meals" },
            { name: "Short Walk", duration: 5, icon: "Footprints", category: "Breaks & Meals" },
            { name: "Client Project B - Focused Work", duration: 90, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Business Admin & Invoicing", duration: 30, icon: "PenTool", category: "Work & Focus" },
            { name: "Workout or Hobby", duration: 60, icon: "Dumbbell", category: "Health & Wellness" },
            { name: "Dinner", duration: 45, icon: "Utensils", category: "Evening Wind-down" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Wind-down" },
            { name: "Skill Development", duration: 45, icon: "BookOpen", category: "Evening Wind-down" },
            { name: "Tidy Workspace", duration: 10, icon: "Wrench", category: "Bedtime Routine" },
            { name: "Disconnect from Work", duration: 30, icon: "Smartphone", category: "Bedtime Routine" },
            { name: "Bedtime", duration: 0, icon: "Bed", category: "Bedtime Routine" },
        ],
        "Healthcare Professional": healthcareRoutine,
        "Day Off - Analyst": dayOffRoutine,
        "Day Off - Healthcare": dayOffRoutineHealthcare,
        "Admin Day - On The Go": businessProfessionalRoutine,
        "Day Off": dayOffRoutine,
        "IT Professional": technicalProfessionalRoutine,
        "Manager": businessProfessionalRoutine,
        "Marketer": businessProfessionalRoutine,
        "Researcher": [
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
            { name: "Freshen Up & Get Ready", duration: 15, icon: "ShowerHead", category: "Morning Routine" },
            { name: "Breakfast", duration: 20, icon: "Utensils", category: "Morning Routine" },
            { name: "Review Literature", duration: 45, icon: "BookOpen", category: "Morning Routine" },
            { name: "Formulate Hypothesis", duration: 30, icon: "Wand2", category: "Morning Routine" },
            { name: "Data Collection / Experiment", duration: 120, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Data Analysis", duration: 90, icon: "ListChecks", category: "Work & Focus" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Work & Focus" },
            { name: "Lunch", duration: 25, icon: "Utensils", category: "Breaks & Meals" },
            { name: "Short Walk", duration: 5, icon: "Footprints", category: "Breaks & Meals" },
            { name: "Writing & Documentation", duration: 90, icon: "PenTool", category: "Work & Focus" },
            { name: "Collaborator Meetings", duration: 30, icon: "Users", category: "Work & Focus" },
            { name: "Walk to clear head", duration: 30, icon: "Footprints", category: "Health & Wellness" },
            { name: "Dinner", duration: 45, icon: "Utensils", category: "Evening Wind-down" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Wind-down" },
            { name: "Unrelated Reading/Learning", duration: 60, icon: "BookOpen", category: "Evening Wind-down" },
            { name: "Lab Cleanup / Prep for Tomorrow", duration: 15, icon: "Wrench", category: "Bedtime Routine" },
            { name: "Relax", duration: 30, icon: "Wind", category: "Bedtime Routine" },
            { name: "Bedtime", duration: 0, icon: "Bed", category: "Bedtime Routine" },
        ],
        "Sales": onTheGoRoutine,
        "Software Engineer": technicalProfessionalRoutine,
        "Student": [
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Morning Routine" },
            { name: "Freshen Up & Get Ready", duration: 15, icon: "ShowerHead", category: "Morning Routine" },
            { name: "Breakfast", duration: 15, icon: "Utensils", category: "Morning Routine" },
            { name: "Review class schedule & assignments", duration: 20, icon: "ListChecks", category: "Morning Routine" },
            { name: "Attend Class / Lecture", duration: 90, icon: "Users", category: "Work & Focus" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Work & Focus" },
            { name: "Lunch", duration: 25, icon: "Utensils", category: "Breaks & Meals" },
            { name: "Short Walk", duration: 5, icon: "Footprints", category: "Breaks & Meals" },
            { name: "Library Study Session 1", duration: 120, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Work on Assignments/Projects", duration: 90, icon: "PenTool", category: "Work & Focus" },
            { name: "Library Study Session 2", duration: 120, icon: "BrainCircuit", category: "Work & Focus" },
            { name: "Sports or Gym", duration: 60, icon: "Dumbbell", category: "Health & Wellness" },
            { name: "Dinner", duration: 45, icon: "Utensils", category: "Evening Wind-down" },
            { name: "Drink a glass of water", duration: 1, icon: "Droplets", category: "Evening Wind-down" },
            { name: "Socializing or Club Activities", duration: 90, icon: "Users", category: "Evening Wind-down" },
            { name: "Pack bag for tomorrow", duration: 10, icon: "ShoppingBag", category: "Bedtime Routine" },
            { name: "Light reading for fun", duration: 20, icon: "BookOpen", category: "Bedtime Routine" },
            { name: "Bedtime", duration: 0, icon: "Bed", category: "Bedtime Routine" },
        ],
        "Writer": creativeProfessionalRoutine,
        "Medical Representative": onTheGoRoutine,
        "Delivery Agent": onTheGoRoutine,
        "General": [
            { name: 'Drink a glass of water', duration: 1, icon: 'Droplets', category: 'Morning Routine' },
            { name: "Freshen Up & Get Ready", duration: 15, icon: "ShowerHead", category: "Morning Routine" },
            { name: 'Breakfast', duration: 20, icon: 'Utensils', category: 'Morning Routine' },
            { name: 'Plan Day', duration: 15, icon: 'ListChecks', category: 'Morning Routine' },
            { name: 'Deep Work', duration: 90, icon: 'BrainCircuit', category: 'Work & Focus' },
            { name: 'Check Emails', duration: 15, icon: 'Mail', category: 'Work & Focus' },
            { name: 'Drink a glass of water', duration: 1, icon: 'Droplets', category: 'Work & Focus' },
            { name: 'Lunch', duration: 25, icon: 'Utensils', category: 'Breaks & Meals' },
            { name: 'Short Walk', duration: 5, icon: 'Footprints', category: 'Breaks & Meals' },
            { name: 'Workout', duration: 45, icon: 'Dumbbell', category: 'Health & Wellness' },
            { name: 'Dinner', duration: 30, icon: 'Utensils', category: 'Evening Wind-down' },
            { name: 'Drink a glass of water', duration: 1, icon: 'Droplets', category: 'Evening Wind-down' },
            { name: 'Read a Book', duration: 30, icon: 'BookOpen', category: 'Evening Wind-down' },
            { name: 'Wind Down', duration: 15, icon: 'Bed', category: 'Bedtime Routine' }
        ]
    }
};

export const profileToRoutineMap: { [key: string]: keyof typeof defaultRoutines.routines } = {
    "Analyst": "Analyst",
    "Artist": "Artist",
    "Consultant": "Consultant",
    "Content Creator": "Content Creator",
    "Designer": "Designer",
    "Educator": "Educator",
    "Entrepreneur": "Entrepreneur",
    "Freelancer": "Freelancer",
    "General": "General",
    "Healthcare Professional": "Healthcare Professional",
    "Day Off": "Day Off",
    "Day Off - Analyst": "Day Off - Analyst",
    "Day Off - Healthcare": "Day Off - Healthcare",
    "Admin Day - On The Go": "Admin Day - On The Go",
    "IT Professional": "IT Professional",
    "Manager": "Manager",
    "Marketer": "Marketer",
    "Researcher": "Researcher",
    "Sales": "Sales",
    "Software Engineer": "Software Engineer",
    "Student": "Student",
    "Writer": "Writer",
    "Medical Representative": "Medical Representative",
    "Delivery Agent": "Delivery Agent"
};

export const categoryConfig: { [key: string]: { color: string, order: number } } = {
    'Morning Routine': { color: 'bg-sky-800 text-sky-100', order: 1 },
    'Primary Work Session': { color: 'bg-blue-800 text-blue-100', order: 2 },
    'Lunch Break': { color: 'bg-orange-800 text-orange-100', order: 3 },
    'Afternoon Session': { color: 'bg-indigo-800 text-indigo-100', order: 4 },
    'Post-Work Decompression': { color: 'bg-rose-800 text-rose-100', order: 5 },
    'Evening Routine': { color: 'bg-purple-800 text-purple-100', order: 6 },
    'Bedtime Routine': { color: 'bg-slate-800 text-slate-100', order: 7 },
    'Work & Focus': { color: 'bg-blue-800 text-blue-100', order: 2 },
    'Breaks & Meals': { color: 'bg-orange-800 text-orange-100', order: 3 },
    'Health & Wellness': { color: 'bg-green-800 text-green-100', order: 4 },
    'Evening Wind-down': { color: 'bg-amber-800 text-amber-100', order: 5 },
    // On-the-go
    'Morning Prep': { color: 'bg-sky-800 text-sky-100', order: 1 },
    'On the Road': { color: 'bg-blue-800 text-blue-100', order: 2 },
    'Post-Work Admin': { color: 'bg-indigo-800 text-indigo-100', order: 3 },
    'Evening & Bedtime': { color: 'bg-purple-800 text-purple-100', order: 4 },
    // Healthcare
    'Pre-Shift Routine': { color: 'bg-sky-800 text-sky-100', order: 1 },
    'During Shift': { color: 'bg-blue-800 text-blue-100', order: 2 },
    'Post-Shift Decompression': { color: 'bg-purple-800 text-purple-100', order: 3 },
    // Day Off
    'Morning Recovery': { color: 'bg-sky-800 text-sky-100', order: 1 },
    'Afternoon Life Admin & Recharge': { color: 'bg-green-800 text-green-100', order: 2 },
    'Evening & Bedtime Reset': { color: 'bg-amber-800 text-amber-100', order: 3 },
    'Default': { color: 'bg-slate-800 text-slate-100', order: 99 },
};

export const getAvailableCategories = () => Object.keys(categoryConfig);
export const getAvailableIcons = () => ["ListChecks", "Bed", "StretchHorizontal", "Dumbbell", "BrainCircuit", "Mail", "Users", "Coffee", "Footprints", "Wind", "Droplets", "BookOpen", "Utensils", "Target", "Wrench", "ShoppingBag", "Gamepad2", "Eye", "PenTool", "Smartphone", "Car", "Tv", "Apple", "ShowerHead", "Truck", "FileCode", "PenSquare", "Puzzle", "Lightbulb", "Presentation", "BarChart", "ShoppingCart", "Headphones", "Power", "Map", "Wand2", "Camera", "Briefcase", "Megaphone", "Stethoscope", "Laptop", "Code", "FlaskConical", "School", "Network", "GraduationCap", "TrendingUp", "Package"];
